ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@stellar/stellar-sdk'
  - bcrypt
  - blake-hash
  - bufferutil
  - msw
  - protobufjs
  - tiny-secp256k1
  - usb
  - utf-8-validate
